/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:12:06 GMT 2018
 */

package com.github.arucard21.epox.av;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.av.AudioTrack;
import com.github.arucard21.epox.av.GenericTrack;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AudioTrack_ESTest extends AudioTrack_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AudioTrack audioTrack0 = null;
      try {
        audioTrack0 = new AudioTrack((GenericTrack) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.av.GenericTrack", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GenericTrack genericTrack0 = new GenericTrack();
      AudioTrack audioTrack0 = new AudioTrack(genericTrack0);
      assertFalse(audioTrack0.def);
  }
}
