/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:06:58 GMT 2018
 */

package com.github.arucard21.epox.av;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.av.FileInfo;
import java.util.Vector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.xml.sax.ext.Attributes2Impl;
import org.xml.sax.helpers.AttributesImpl;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileInfo_ESTest extends FileInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo(",UB)0F.5");
      Vector<String> vector0 = new Vector<String>();
      fileInfo0.aud = vector0;
      vector0.add(",UB)0F.5");
      // Undeclared exception!
      try { 
        fileInfo0.convert("com.github.arucard21.epox.webaom.FileHandler", 1);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.github.arucard21.epox.webaom.data.AMap
         //
         verifyException("com.github.arucard21.epox.av.FileInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("");
      FileInfo.MyHandler fileInfo_MyHandler0 = fileInfo0.new MyHandler();
      char[] charArray0 = new char[2];
      // Undeclared exception!
      try { 
        fileInfo_MyHandler0.characters(charArray0, 0, 10);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo(": ");
      FileInfo.MyHandler fileInfo_MyHandler0 = fileInfo0.new MyHandler();
      AttributesImpl attributesImpl0 = new AttributesImpl();
      fileInfo_MyHandler0.startElement("", "0\u0000b>A\"QPONJ(T.", "sub", attributesImpl0);
      fileInfo_MyHandler0.endElement("rp&.GzmeL;ZvqI", "#yOhFa", "aud");
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("+4+xW");
      Vector<String> vector0 = new Vector<String>();
      fileInfo0.vid = vector0;
      vector0.add((String) null);
      // Undeclared exception!
      try { 
        fileInfo0.dump();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.av.FileInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("null");
      fileInfo0.sub = null;
      // Undeclared exception!
      try { 
        fileInfo0.convert("^Or/;", 2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.av.FileInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("+4+xW");
      Vector<String> vector0 = new Vector<String>();
      vector0.add("com.github.arucard21.epox.av.FileInfo");
      fileInfo0.vid = vector0;
      // Undeclared exception!
      try { 
        fileInfo0.convert("+4+xW", 0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.github.arucard21.epox.webaom.data.AMap
         //
         verifyException("com.github.arucard21.epox.av.FileInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("");
      // Undeclared exception!
      try { 
        fileInfo0.byXml((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.StringReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FileInfo fileInfo0 = null;
      try {
        fileInfo0 = new FileInfo((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.StringReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("}H7d/");
      fileInfo0.byXml("tL.~i");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("+4+xW");
      Vector<String> vector0 = new Vector<String>();
      fileInfo0.vid = vector0;
      vector0.add((String) null);
      String string0 = fileInfo0.convert("+4+xW", 0);
      assertNotNull(string0);
      assertEquals("+4+xW", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("'t.");
      String string0 = fileInfo0.convert("aud", 2);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("}H7d/");
      String string0 = fileInfo0.convert("aud", (-1981));
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("99O|");
      String string0 = fileInfo0.convert((String) null, 0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("com.github.arucard21.epox.av.FileInfo");
      FileInfo.MyHandler fileInfo_MyHandler0 = fileInfo0.new MyHandler();
      char[] charArray0 = new char[7];
      fileInfo_MyHandler0.characters(charArray0, 0, 0);
      assertArrayEquals(new char[] {'\u0000', '\u0000', '\u0000', '\u0000', '\u0000', '\u0000', '\u0000'}, charArray0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("");
      FileInfo.MyHandler fileInfo_MyHandler0 = fileInfo0.new MyHandler();
      char[] charArray0 = new char[9];
      charArray0[1] = '[';
      fileInfo_MyHandler0.characters(charArray0, 1, 1);
      assertArrayEquals(new char[] {'\u0000', '[', '\u0000', '\u0000', '\u0000', '\u0000', '\u0000', '\u0000', '\u0000'}, charArray0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo(": ");
      FileInfo.MyHandler fileInfo_MyHandler0 = fileInfo0.new MyHandler();
      AttributesImpl attributesImpl0 = new AttributesImpl();
      fileInfo_MyHandler0.startElement("", "0\u0000b>A\"QPONJ(T.", "sub", attributesImpl0);
      fileInfo_MyHandler0.endElement("I~IJO/{-}qSAS?", ".", "sub");
      fileInfo_MyHandler0.startElement("+{{AJW!e(", "0\u0000b>A\"QPONJ(T.", "sub", attributesImpl0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo(": ");
      FileInfo.MyHandler fileInfo_MyHandler0 = fileInfo0.new MyHandler();
      fileInfo_MyHandler0.endElement("rp&.GzmeL;ZvqI", "#yOhFa", "aud");
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo(": ");
      FileInfo.MyHandler fileInfo_MyHandler0 = fileInfo0.new MyHandler();
      fileInfo_MyHandler0.endElement("I~IJO/{-}qSAS?", ".", "sub");
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo(": ");
      FileInfo.MyHandler fileInfo_MyHandler0 = fileInfo0.new MyHandler();
      AttributesImpl attributesImpl0 = new AttributesImpl();
      fileInfo_MyHandler0.startElement("sub", "com.github.arucard21.epox.webaom.FileHandler$FileFilter1", "default", attributesImpl0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("");
      FileInfo.MyHandler fileInfo_MyHandler0 = fileInfo0.new MyHandler();
      Attributes2Impl attributes2Impl0 = new Attributes2Impl();
      fileInfo_MyHandler0.startElement(".#EK2Cp9", ".#EK2Cp9", "aud", attributes2Impl0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo(": ");
      FileInfo.MyHandler fileInfo_MyHandler0 = fileInfo0.new MyHandler();
      AttributesImpl attributesImpl0 = new AttributesImpl();
      fileInfo_MyHandler0.startElement("", "0\u0000b>A\"QPONJ(T.", "sub", attributesImpl0);
      fileInfo_MyHandler0.startElement("sub", "=:B5opqaI`U,M2B;;7", "com.github.arucard21.epox.webaom.data.AMap", attributesImpl0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("+4+xW");
      Vector<Integer> vector0 = new Vector<Integer>();
      fileInfo0.sub = vector0;
      Integer integer0 = new Integer(0);
      vector0.add(integer0);
      // Undeclared exception!
      try { 
        fileInfo0.dump();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Integer cannot be cast to [[Ljava.lang.String;
         //
         verifyException("com.github.arucard21.epox.av.FileInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("");
      fileInfo0.dump();
  }
}
