/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:12:17 GMT 2018
 */

package com.github.arucard21.epox.av;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.av.GenericTrack;
import com.github.arucard21.epox.av.VideoTrack;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VideoTrack_ESTest extends VideoTrack_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VideoTrack videoTrack0 = null;
      try {
        videoTrack0 = new VideoTrack((GenericTrack) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.av.GenericTrack", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GenericTrack genericTrack0 = new GenericTrack();
      VideoTrack videoTrack0 = new VideoTrack(genericTrack0);
      assertEquals(0.0F, videoTrack0.dur, 0.01F);
  }
}
