/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:05:48 GMT 2018
 */

package com.github.arucard21.epox.webaom.net;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.arucard21.epox.webaom.net.AConEx;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AConEx_ESTest extends AConEx_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AConEx aConEx0 = new AConEx((-2312), "Unknown Error.");
      boolean boolean0 = aConEx0.is(473);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = AConEx.defaultMsg(473);
      assertEquals("Unknown Error.", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = AConEx.defaultMsg(5);
      assertEquals("Unknown Error.", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = AConEx.defaultMsg(0);
      assertEquals("This version of WebAOM is no longer supported! Check WIKI.", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = AConEx.defaultMsg(1);
      assertEquals("A new version of WebAOM is out. Check WIKI!", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = AConEx.defaultMsg(8);
      assertEquals("Decryption failed. The connection timed out (most likely).", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = AConEx.defaultMsg(7);
      assertEquals("Internal Server Error @ AniDB!", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = AConEx.defaultMsg(6);
      assertEquals("AniDB is out of service! Try again next year.", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AConEx aConEx0 = new AConEx(5);
      assertEquals(4, AConEx.CLIENT_USER);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = AConEx.defaultMsg(4);
      assertEquals("Unknown Error.", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = AConEx.defaultMsg(3);
      assertEquals("Unknown Error.", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = AConEx.defaultMsg(2);
      assertEquals("Unknown Error.", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AConEx aConEx0 = new AConEx(473);
      boolean boolean0 = aConEx0.is(473);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      AConEx aConEx0 = new AConEx(1837);
      boolean boolean0 = aConEx0.is((-3406));
      assertFalse(boolean0);
  }
}
