/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:11:35 GMT 2018
 */

package com.github.arucard21.epox.webaom.net;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.arucard21.epox.webaom.net.TagEx;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TagEx_ESTest extends TagEx_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TagEx tagEx0 = new TagEx();
  }
}
