/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:11:31 GMT 2018
 */

package com.github.arucard21.epox.webaom.data;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.webaom.data.AG;
import com.github.arucard21.epox.webaom.data.Anime;
import com.github.arucard21.epox.webaom.data.Group;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AG_ESTest extends AG_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Anime anime0 = new Anime(69);
      Group group0 = new Group(69);
      AG aG0 = new AG(anime0, group0);
      anime0.eps = 69;
      aG0.add(group0);
      int int0 = aG0.getPct();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Anime anime0 = new Anime((-1));
      Group group0 = new Group((-1));
      AG aG0 = new AG(anime0, group0);
      anime0.eps = (-1);
      aG0.add(group0);
      int int0 = aG0.getPct();
      assertEquals((-100), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Group group0 = Group.none;
      AG aG0 = new AG((Anime) null, group0);
      // Undeclared exception!
      try { 
        aG0.getPct();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.data.AG", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Anime anime0 = new Anime(0);
      AG aG0 = null;
      try {
        aG0 = new AG(anime0, (Group) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.data.AG", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Anime anime0 = new Anime((-3837));
      Group group0 = new Group(0);
      AG aG0 = new AG(anime0, group0);
      String string0 = aG0.toString();
      assertEquals(0, aG0.id);
      assertEquals("none ()", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Anime anime0 = new Anime((-3837));
      Group group0 = new Group(0);
      AG aG0 = new AG(anime0, group0);
      int int0 = aG0.getPct();
      assertEquals(0, aG0.id);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Anime anime0 = new Anime((-3837));
      Group group0 = new Group(0);
      AG aG0 = new AG(anime0, group0);
      anime0.eps = 948;
      int int0 = aG0.getPct();
      assertEquals(0, int0);
      assertEquals(0, aG0.id);
  }
}
