/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:10:42 GMT 2018
 */

package com.github.arucard21.epox.webaom.data;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.webaom.data.AMap;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AMap_ESTest extends AMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AMap aMap0 = new AMap();
      aMap0.put("", "9");
      aMap0.put("", "");
      assertEquals(1, aMap0.size());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AMap aMap0 = new AMap();
      aMap0.put("uX/.C|Errn| P2", "");
      aMap0.put("uX/.C|Errn| P2", "uX/.C|Errn| P2");
      assertEquals(1, aMap0.size());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AMap aMap0 = new AMap();
      aMap0.put((String) null, "0o~NU9e-j@M:H.O");
      aMap0.put((String) null, 0L);
      assertFalse(aMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AMap aMap0 = new AMap();
      aMap0.put("<", "<");
      aMap0.put("<", 2817);
      assertFalse(aMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AMap aMap0 = new AMap();
      Set set0 = aMap0.keySet();
      aMap0.putIfAbsent(set0, set0);
      // Undeclared exception!
      try { 
        aMap0.toArray();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.util.HashMap$KeySet cannot be cast to java.lang.String
         //
         verifyException("com.github.arucard21.epox.webaom.data.AMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AMap aMap0 = new AMap();
      Integer integer0 = new Integer(49);
      aMap0.put("", integer0);
      // Undeclared exception!
      try { 
        aMap0.put("", "");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Integer cannot be cast to java.lang.String
         //
         verifyException("com.github.arucard21.epox.webaom.data.AMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AMap aMap0 = new AMap();
      Set set0 = aMap0.entrySet();
      aMap0.put("zZ^Ow=!E)xHuQwX", set0);
      // Undeclared exception!
      try { 
        aMap0.put("zZ^Ow=!E)xHuQwX", 0L);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.util.HashMap$EntrySet cannot be cast to java.lang.String
         //
         verifyException("com.github.arucard21.epox.webaom.data.AMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AMap aMap0 = new AMap();
      Object object0 = new Object();
      aMap0.putIfAbsent(")QsiU~LzwZ5Mk`'K", object0);
      // Undeclared exception!
      try { 
        aMap0.put(")QsiU~LzwZ5Mk`'K", 0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to java.lang.String
         //
         verifyException("com.github.arucard21.epox.webaom.data.AMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AMap aMap0 = new AMap();
      aMap0.put("<", "<");
      aMap0.toArray();
      assertEquals(1, aMap0.size());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AMap aMap0 = new AMap();
      String[][] stringArray0 = aMap0.toArray();
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AMap aMap0 = new AMap();
      aMap0.put("<", (String) null);
      assertTrue(aMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AMap aMap0 = new AMap();
      aMap0.put((String) null, 733L);
      assertFalse(aMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AMap aMap0 = new AMap();
      aMap0.put(")QsiU~LzwZ5Mk`'K", 0);
      assertFalse(aMap0.isEmpty());
  }
}
