/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:07:47 GMT 2018
 */

package com.github.arucard21.epox.webaom.data;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.webaom.data.Ep;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ep_ESTest extends Ep_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Ep ep0 = new Ep(0);
      ep0.kan = "0|null|null|null|null";
      String string0 = ep0.serialize();
      assertEquals("0|null|null|null|0|null|null|null|null", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Ep ep0 = new Ep(0);
      ep0.rom = "Yg8+zk{;t";
      String string0 = ep0.serialize();
      assertEquals("0|null|null|Yg8+zk{;t|null", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Ep ep0 = new Ep(0);
      Ep.TPRI = 1;
      String string0 = ep0.serialize();
      assertEquals("0|null|null|null|null", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Ep ep0 = new Ep(0);
      ep0.eng = "null - null";
      String string0 = ep0.toString();
      assertEquals(0, ep0.id);
      assertEquals("null - null - null", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Ep.TPRI = 2;
      Ep ep0 = new Ep(2);
      ep0.eng = "";
      // Undeclared exception!
      try { 
        ep0.compareTo((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Ep.TPRI = 2;
      Ep ep0 = new Ep(2);
      ep0.num = "7HM#V4wR";
      // Undeclared exception!
      try { 
        ep0.compareTo((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Ep ep0 = new Ep(0);
      Ep.TPRI = 1;
      ep0.eng = "0|null|null|null|null";
      String string0 = ep0.toString();
      assertEquals("null - 0|null|null|null|null", string0);
      assertEquals(0, ep0.id);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Ep ep0 = new Ep(0);
      ep0.kan = "0|null|null|null|null";
      Ep.TPRI = 1;
      String string0 = ep0.toString();
      assertEquals("null - null", string0);
      assertEquals(0, ep0.id);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[5];
      stringArray0[0] = "20";
      stringArray0[1] = "";
      Ep ep0 = new Ep(stringArray0);
      assertEquals(0, Ep.TPRI);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[5];
      stringArray0[0] = "20";
      Ep ep0 = null;
      try {
        ep0 = new Ep(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.data.Ep", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Ep ep0 = new Ep(0);
      ep0.num = " (";
      ep0.compareTo(ep0);
      assertEquals(0, ep0.id);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Ep ep0 = new Ep(124);
      ep0.num = "";
      int int0 = ep0.compareTo(" - ");
      assertEquals(124, ep0.id);
      assertEquals((-74), int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[7];
      Ep ep0 = null;
      try {
        ep0 = new Ep(stringArray0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Integer", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Ep ep0 = null;
      try {
        ep0 = new Ep(stringArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("com.github.arucard21.epox.webaom.data.Ep", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Ep ep0 = new Ep(0);
      Ep.TPRI = 1;
      ep0.rom = "Yg8+zk{;t";
      String string0 = ep0.toString();
      assertEquals("null - Yg8+zk{;t", string0);
      assertEquals(0, ep0.id);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Ep.TPRI = 2;
      Ep ep0 = new Ep(2);
      ep0.kan = ">";
      String string0 = ep0.toString();
      assertEquals("null - >", string0);
      assertEquals(2, ep0.id);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Ep ep0 = new Ep((-7));
      Ep.TPRI = 1;
      ep0.rom = "Yg8Uzk{;;t";
      int int0 = ep0.compareTo("Yg8Uzk{;;t");
      assertEquals((-7), ep0.id);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Ep.TPRI = 2;
      Ep ep0 = new Ep(2);
      String string0 = ep0.toString();
      assertEquals(2, ep0.id);
      assertEquals("null - null", string0);
  }
}
