/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:12:14 GMT 2018
 */

package com.github.arucard21.epox.webaom.data;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.arucard21.epox.webaom.data.Group;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Group_ESTest extends Group_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Group group0 = new Group((-1));
      String string0 = group0.serialize();
      assertEquals("none|", string0);
      assertEquals((-1), group0.id);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Group group0 = new Group((-1));
      String string0 = group0.none.toString();
      assertEquals("none|", string0);
      assertEquals((-1), group0.id);
  }
}
