/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:10:15 GMT 2018
 */

package com.github.arucard21.epox.swing;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.swing.CommandModel;
import com.github.arucard21.epox.swing.JPanelCommand;
import com.github.arucard21.epox.swing.Log;
import com.github.arucard21.epox.webaom.ChiiEmu;
import com.github.arucard21.epox.webaom.net.ACon;
import com.github.arucard21.epox.webaom.net.AConS;
import java.awt.event.ActionEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JPanelCommand_ESTest extends JPanelCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JPanelCommand jPanelCommand0 = new JPanelCommand((CommandModel) null, " votes, ");
      jPanelCommand0.println(" votes, ");
      assertFalse(jPanelCommand0.isFocusTraversalPolicySet());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AConS aConS0 = new AConS("comboBoxEdited", 2886, 2886, 2886, (-1739999318), 2886, true);
      ACon aCon0 = new ACon((Log) null, aConS0);
      ChiiEmu chiiEmu0 = new ChiiEmu(aCon0);
      JPanelCommand jPanelCommand0 = new JPanelCommand(chiiEmu0, "comboBoxEdited");
      ActionEvent actionEvent0 = new ActionEvent("comboBoxEdited", 71, "comboBoxEdited", 0L, (-190));
      // Undeclared exception!
      try { 
        jPanelCommand0.actionPerformed(actionEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ChiiEmu chiiEmu0 = new ChiiEmu((ACon) null);
      JPanelCommand jPanelCommand0 = new JPanelCommand(chiiEmu0, "<n8`*MZI5");
      ActionEvent actionEvent0 = new ActionEvent("<n8`*MZI5", (-1739999318), "z'4v+:T_SC^mDV", (-1739999318), (-972));
      jPanelCommand0.actionPerformed(actionEvent0);
      assertFalse(jPanelCommand0.isFocusTraversalPolicySet());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ChiiEmu chiiEmu0 = new ChiiEmu((ACon) null);
      JPanelCommand jPanelCommand0 = new JPanelCommand(chiiEmu0, "$^");
      jPanelCommand0.status1("South");
      assertFalse(jPanelCommand0.isFocusTraversalPolicySet());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ChiiEmu chiiEmu0 = new ChiiEmu((ACon) null);
      JPanelCommand jPanelCommand0 = new JPanelCommand(chiiEmu0, "$^");
      jPanelCommand0.status0((String) null);
      assertTrue(jPanelCommand0.getFocusTraversalKeysEnabled());
  }
}
