/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:10:13 GMT 2018
 */

package com.github.arucard21.epox.swing;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.arucard21.epox.swing.JPanelDebug;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JPanelDebug_ESTest extends JPanelDebug_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JPanelDebug jPanelDebug0 = new JPanelDebug("");
      JPanelDebug.Updater jPanelDebug_Updater0 = jPanelDebug0.new Updater();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JPanelDebug jPanelDebug0 = new JPanelDebug((String) null, true, true, false, false);
      assertFalse(jPanelDebug0.isFocusTraversalPolicySet());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JPanelDebug jPanelDebug0 = new JPanelDebug("Wu%vX>y(7Zo8/S&UVo", false, false, false, false);
      JPanelDebug.Updater jPanelDebug_Updater0 = jPanelDebug0.updater;
      jPanelDebug_Updater0.run();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JPanelDebug jPanelDebug0 = new JPanelDebug((String) null);
      jPanelDebug0.list();
      assertFalse(jPanelDebug0.isFocusTraversalPolicyProvider());
  }
}
