/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:12:06 GMT 2018
 */

package com.github.arucard21.epox.swing;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.swing.JScrollTable;
import java.awt.event.MouseWheelEvent;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JScrollTable_ESTest extends JScrollTable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JTable jTable0 = new JTable(702, 702);
      JScrollTable jScrollTable0 = new JScrollTable(jTable0);
      int int0 = jScrollTable0.getTopVisibleRow();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JTable jTable0 = new JTable();
      JScrollTable jScrollTable0 = new JScrollTable(jTable0);
      int int0 = jScrollTable0.getTopVisibleRow();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JTable jTable0 = new JTable();
      JScrollTable jScrollTable0 = new JScrollTable(jTable0);
      int int0 = jScrollTable0.getBottomVisibleRow();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JScrollTable jScrollTable0 = new JScrollTable((JTable) null);
      // Undeclared exception!
      try { 
        jScrollTable0.getBottomVisibleRow();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.swing.JScrollTable", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JTable jTable0 = new JTable(594, 0);
      JScrollTable jScrollTable0 = new JScrollTable(jTable0);
      int int0 = jScrollTable0.getBottomVisibleRow();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TableModel tableModel0 = mock(TableModel.class, new ViolatedAssumptionAnswer());
      doReturn(1204, 0).when(tableModel0).getColumnCount();
      doReturn((String) null).when(tableModel0).getColumnName(anyInt());
      doReturn((-1), 1204).when(tableModel0).getRowCount();
      JTable jTable0 = new JTable(tableModel0);
      JScrollTable jScrollTable0 = new JScrollTable(jTable0);
      int int0 = jScrollTable0.getBottomVisibleRow();
      assertEquals(1203, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JScrollTable jScrollTable0 = new JScrollTable((JTable) null);
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent(jScrollTable0, 1315, 1315, 1315, 1315, 0, (-258), 0, 0, false, 1315, (-2162), (-2162));
      jScrollTable0.mouseClicked(mouseWheelEvent0);
      assertEquals(0, mouseWheelEvent0.getClickCount());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JTable jTable0 = new JTable((Vector) null, (Vector) null);
      JScrollTable jScrollTable0 = new JScrollTable(jTable0);
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent(jScrollTable0, (-25), 0L, (-1), (-593), (-1), (-593), false, 0, (-1), 711);
      jScrollTable0.mouseExited(mouseWheelEvent0);
      assertFalse(jScrollTable0.isFocusTraversalPolicySet());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JScrollTable jScrollTable0 = new JScrollTable((JTable) null);
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent(jScrollTable0, 1315, 1315, 1315, 1315, 0, (-258), 0, 0, false, 1315, (-2162), (-2162));
      jScrollTable0.mouseEntered(mouseWheelEvent0);
      assertEquals(0, mouseWheelEvent0.getButton());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JScrollTable jScrollTable0 = new JScrollTable((JTable) null);
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent(jScrollTable0, 1315, 1315, 1315, 1315, 0, (-258), 0, 0, false, 1315, (-2162), (-2162));
      jScrollTable0.mousePressed(mouseWheelEvent0);
      assertFalse(jScrollTable0.isFocusTraversalPolicyProvider());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JTable jTable0 = new JTable((Vector) null, (Vector) null);
      JScrollTable jScrollTable0 = new JScrollTable(jTable0);
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent(jScrollTable0, (-25), 0L, (-1), (-593), (-1), (-593), false, 0, (-1), 711);
      jScrollTable0.mouseReleased(mouseWheelEvent0);
      assertFalse(jScrollTable0.isFocusTraversalPolicySet());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JScrollTable jScrollTable0 = new JScrollTable((JTable) null);
      // Undeclared exception!
      try { 
        jScrollTable0.getTopVisibleRow();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.swing.JScrollTable", e);
      }
  }
}
