/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:11:05 GMT 2018
 */

package com.github.arucard21.epox.swing;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.arucard21.epox.swing.SortButtonRenderer;
import java.awt.Component;
import java.util.Stack;
import java.util.Vector;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SortButtonRenderer_ESTest extends SortButtonRenderer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SortButtonRenderer sortButtonRenderer0 = new SortButtonRenderer();
      Vector<JSpinner.DateEditor> vector0 = new Vector<JSpinner.DateEditor>();
      Stack<String> stack0 = new Stack<String>();
      JTable jTable0 = new JTable(vector0, stack0);
      SortButtonRenderer sortButtonRenderer1 = (SortButtonRenderer)sortButtonRenderer0.getTableCellRendererComponent(jTable0, jTable0, false, true, 1, (-2348));
      assertFalse(sortButtonRenderer1.isFocusCycleRoot());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JTable jTable0 = new JTable();
      JTableHeader jTableHeader0 = jTable0.getTableHeader();
      SortButtonRenderer sortButtonRenderer0 = new SortButtonRenderer();
      sortButtonRenderer0.setPressedColumn(1748);
      SortButtonRenderer sortButtonRenderer1 = (SortButtonRenderer)sortButtonRenderer0.getTableCellRendererComponent(jTable0, jTableHeader0, true, false, 1748, 1748);
      assertFalse(sortButtonRenderer1.isFocusTraversalPolicySet());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SortButtonRenderer sortButtonRenderer0 = new SortButtonRenderer();
      Component component0 = sortButtonRenderer0.getTableCellRendererComponent((JTable) null, (Object) null, true, true, (-1), (-1));
      assertSame(sortButtonRenderer0, component0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SortButtonRenderer sortButtonRenderer0 = new SortButtonRenderer();
      Component component0 = sortButtonRenderer0.getTableCellRendererComponent((JTable) null, sortButtonRenderer0, true, true, (-1), 2108);
      assertTrue(component0.getFocusTraversalKeysEnabled());
  }
}
