/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:03:45 GMT 2018
 */

package com.github.arucard21.epox.swing;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.swing.TableModelSortable;
import com.github.arucard21.epox.swing.TableSorter;
import com.github.arucard21.epox.webaom.JobList;
import com.github.arucard21.epox.webaom.ui.TableModelJobs;
import java.math.BigInteger;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableSorter_ESTest extends TableSorter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      TableSorter tableSorter0 = new TableSorter(tableModelJobs0);
      int[] intArray0 = new int[3];
      // Undeclared exception!
      try { 
        tableSorter0.sort(intArray0, 1587, false);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("com.github.arucard21.epox.swing.TableSorter", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      TableSorter tableSorter0 = new TableSorter(tableModelJobs0);
      int[] intArray0 = new int[7];
      tableSorter0.sort(intArray0, (-708), true);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      TableSorter tableSorter0 = new TableSorter(tableModelJobs0);
      tableSorter0.compare0(0, 0, (-1));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      TableSorter tableSorter0 = new TableSorter(tableModelJobs0);
      tableSorter0.compare(16, 4);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      TableSorter tableSorter0 = new TableSorter(tableModelJobs0);
      int[] intArray0 = new int[13];
      // Undeclared exception!
      try { 
        tableSorter0.sort0(intArray0, 2, 21037058);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 10518530
         //
         verifyException("com.github.arucard21.epox.swing.TableSorter", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableSorter tableSorter0 = new TableSorter(jobList0.jlm);
      // Undeclared exception!
      try { 
        tableSorter0.compare0(34, 0, (-751));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.swing.TableSorter", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableSorter tableSorter0 = new TableSorter(jobList0.jlm);
      // Undeclared exception!
      try { 
        tableSorter0.compare((Number) 18, (Number) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.swing.TableSorter", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TableSorter tableSorter0 = new TableSorter((TableModelSortable) null);
      // Undeclared exception!
      try { 
        tableSorter0.compare(32, (-1758));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.swing.TableSorter", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      TableSorter tableSorter0 = new TableSorter(tableModelJobs0);
      tableSorter0.compare0(0, 12, 1246);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      TableSorter tableSorter0 = new TableSorter(tableModelJobs0);
      tableSorter0.compare(1, 1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      TableSorter tableSorter0 = new TableSorter(tableModelJobs0);
      tableSorter0.compare(2, 15);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableSorter tableSorter0 = new TableSorter(jobList0.jlm);
      tableSorter0.reset();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableSorter tableSorter0 = new TableSorter(jobList0.jlm);
      BigInteger bigInteger0 = BigInteger.ZERO;
      tableSorter0.compare((Number) 11, (Number) bigInteger0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableSorter tableSorter0 = new TableSorter(jobList0.jlm);
      tableSorter0.compare((Number) 2, (Number) 13);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableSorter tableSorter0 = new TableSorter(jobList0.jlm);
      tableSorter0.compare((Number) 21, (Number) 21);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      TableSorter tableSorter0 = new TableSorter(tableModelJobs0);
      int[] intArray0 = new int[8];
      // Undeclared exception!
      try { 
        tableSorter0.sort(intArray0, 0, false);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("com.github.arucard21.epox.swing.TableSorter", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      TableSorter tableSorter0 = new TableSorter(tableModelJobs0);
      int[] intArray0 = new int[6];
      // Undeclared exception!
      try { 
        tableSorter0.sort(intArray0, (-32754), false);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("com.github.arucard21.epox.swing.TableSorter", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableSorter tableSorter0 = new TableSorter(jobList0.jlm);
      int[] intArray0 = new int[0];
      tableSorter0.sort(intArray0, 15, true);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableSorter tableSorter0 = new TableSorter(jobList0.jlm);
      int[] intArray0 = new int[6];
      // Undeclared exception!
      try { 
        tableSorter0.sort(intArray0, (-32754), false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.swing.TableSorter", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      TableSorter tableSorter0 = new TableSorter(tableModelJobs0);
      int[] intArray0 = new int[13];
      tableSorter0.sort0(intArray0, 3, 13);
      assertEquals(13, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableSorter tableSorter0 = new TableSorter(jobList0.jlm);
      int[] intArray0 = new int[13];
      // Undeclared exception!
      try { 
        tableSorter0.sort0(intArray0, 3, 13);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.swing.TableSorter", e);
      }
  }
}
