/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:11:02 GMT 2018
 */

package com.github.arucard21.epox.swing;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.swing.UniqueStringList;
import java.util.Vector;
import javax.swing.JComboBox;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UniqueStringList_ESTest extends UniqueStringList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("");
      Integer[] integerArray0 = new Integer[5];
      JComboBox<Integer> jComboBox0 = new JComboBox<Integer>(integerArray0);
      uniqueStringList0.addListDataListener(jComboBox0);
      uniqueStringList0.reset();
      assertEquals(0, uniqueStringList0.getSize());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("qE&f0!");
      Vector<Object> vector0 = new Vector<Object>();
      JComboBox<Object> jComboBox0 = new JComboBox<Object>(vector0);
      uniqueStringList0.addListDataListener(jComboBox0);
      uniqueStringList0.add("qE&f0!");
      uniqueStringList0.add("VkwUoqM");
      uniqueStringList0.add("jql1<");
      String string0 = uniqueStringList0.removeElementAt(2);
      assertEquals("jql1<", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("");
      Vector<Object> vector0 = new Vector<Object>();
      JComboBox<Object> jComboBox0 = new JComboBox<Object>(vector0);
      uniqueStringList0.addListDataListener(jComboBox0);
      uniqueStringList0.add("");
      boolean boolean0 = uniqueStringList0.includes("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("");
      Integer[] integerArray0 = new Integer[5];
      JComboBox<Integer> jComboBox0 = new JComboBox<Integer>(integerArray0);
      uniqueStringList0.addListDataListener(jComboBox0);
      uniqueStringList0.add("@ot1L");
      Object[] objectArray0 = uniqueStringList0.getStrings();
      assertEquals(1, objectArray0.length);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("qE&f0!");
      Vector<Object> vector0 = new Vector<Object>();
      JComboBox<Object> jComboBox0 = new JComboBox<Object>(vector0);
      uniqueStringList0.addListDataListener(jComboBox0);
      uniqueStringList0.add((String) null);
      String string0 = uniqueStringList0.getStringAt(0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("qE&f0!");
      Vector<Object> vector0 = new Vector<Object>();
      JComboBox<Object> jComboBox0 = new JComboBox<Object>(vector0);
      uniqueStringList0.addListDataListener(jComboBox0);
      uniqueStringList0.add("qE&f0!");
      String string0 = uniqueStringList0.getStringAt(0);
      assertEquals("qE&f0!", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("");
      Integer[] integerArray0 = new Integer[5];
      JComboBox<Integer> jComboBox0 = new JComboBox<Integer>(integerArray0);
      uniqueStringList0.addListDataListener(jComboBox0);
      uniqueStringList0.add("@ot1L");
      int int0 = uniqueStringList0.getSize();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("qE&f0!");
      Vector<Object> vector0 = new Vector<Object>();
      JComboBox<Object> jComboBox0 = new JComboBox<Object>(vector0);
      uniqueStringList0.addListDataListener(jComboBox0);
      uniqueStringList0.add((String) null);
      Object object0 = uniqueStringList0.getElementAt(0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("");
      Integer[] integerArray0 = new Integer[5];
      JComboBox<Integer> jComboBox0 = new JComboBox<Integer>(integerArray0);
      uniqueStringList0.addListDataListener(jComboBox0);
      uniqueStringList0.add("@ot1L");
      Object object0 = uniqueStringList0.getElementAt(0);
      assertEquals("@ot1L", object0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("itH4Y7'e");
      // Undeclared exception!
      try { 
        uniqueStringList0.add("itH4Y7'e");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.swing.UniqueStringList", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("");
      Object[] objectArray0 = uniqueStringList0.getStrings();
      assertEquals(0, objectArray0.length);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("qE&f0!");
      int int0 = uniqueStringList0.getSize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("qE&f0!");
      Vector<Object> vector0 = new Vector<Object>();
      JComboBox<Object> jComboBox0 = new JComboBox<Object>(vector0);
      uniqueStringList0.addListDataListener(jComboBox0);
      uniqueStringList0.add("qE&f0!");
      uniqueStringList0.toString();
      assertEquals(1, uniqueStringList0.getSize());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("qE&f0!");
      Vector<Object> vector0 = new Vector<Object>();
      JComboBox<Object> jComboBox0 = new JComboBox<Object>(vector0);
      uniqueStringList0.addListDataListener(jComboBox0);
      uniqueStringList0.add("VkwUoqM");
      uniqueStringList0.add("VkwUoqM");
      assertEquals(1, uniqueStringList0.getSize());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("qE&f0!");
      String string0 = uniqueStringList0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("qE&f0!");
      // Undeclared exception!
      try { 
        uniqueStringList0.removeElementAt(2);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 2
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("qE&f0!");
      // Undeclared exception!
      try { 
        uniqueStringList0.getElementAt(2);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2 >= 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("qE&f0!");
      // Undeclared exception!
      try { 
        uniqueStringList0.getStringAt(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0 >= 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList((String) null);
      JComboBox<Object> jComboBox0 = new JComboBox<Object>();
      uniqueStringList0.removeListDataListener(jComboBox0);
      assertTrue(jComboBox0.getFocusTraversalKeysEnabled());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList("qE&f0!");
      boolean boolean0 = uniqueStringList0.includes("qE&f0!");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      UniqueStringList uniqueStringList0 = new UniqueStringList((String) null);
      // Undeclared exception!
      try { 
        uniqueStringList0.reset();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.swing.UniqueStringList", e);
      }
  }
}
