/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:11:33 GMT 2018
 */

package com.twmacinta.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.twmacinta.util.MD5State;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MD5State_ESTest extends MD5State_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MD5State mD5State0 = new MD5State();
      mD5State0.state = null;
      MD5State mD5State1 = null;
      try {
        mD5State1 = new MD5State(mD5State0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.twmacinta.util.MD5State", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MD5State mD5State0 = new MD5State();
      byte[] byteArray0 = new byte[0];
      mD5State0.buffer = byteArray0;
      MD5State mD5State1 = null;
      try {
        mD5State1 = new MD5State(mD5State0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("com.twmacinta.util.MD5State", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MD5State mD5State0 = new MD5State();
      MD5State mD5State1 = new MD5State(mD5State0);
      assertFalse(mD5State1.equals((Object)mD5State0));
  }
}
