/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:07:22 GMT 2018
 */

package jonelo.jacksum.algorithm;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import jonelo.jacksum.algorithm.Edonkey;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Edonkey_ESTest extends Edonkey_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      edonkey0.length = 7582622308322968760L;
      String string0 = edonkey0.getHexValue();
      assertEquals("be6bc64c94bbc062bcebfb40b4f93304", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      edonkey0.update((byte)105);
      byte[] byteArray0 = new byte[21];
      // Undeclared exception!
      try { 
        edonkey0.update(byteArray0, 1, 9728000);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      byte[] byteArray0 = new byte[2];
      edonkey0.length = 1343L;
      // Undeclared exception!
      try { 
        edonkey0.update(byteArray0, 50, 9728000);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      byte[] byteArray0 = new byte[2];
      edonkey0.update(byteArray0);
      edonkey0.update(byteArray0);
      assertArrayEquals(new byte[] {(byte)0, (byte)0}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      edonkey0.length = (-2621L);
      edonkey0.update((byte)0);
      assertEquals(0L, edonkey0.getValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      edonkey0.length = 9727994L;
      byte[] byteArray0 = new byte[21];
      edonkey0.update(byteArray0);
      assertEquals(21, byteArray0.length);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      // Undeclared exception!
      try { 
        edonkey0.update((byte[]) null, 22, 22);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      byte[] byteArray0 = new byte[3];
      edonkey0.update(byteArray0, (int) (byte) (-121), (int) (byte) (-121));
      // Undeclared exception!
      try { 
        edonkey0.update((byte) (-14));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -57
         //
         verifyException("gnu.crypto.hash.BaseHash", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      String string0 = edonkey0.getHexValue();
      assertEquals("31d6cfe0d16ae931b73c59d7e0c089c0", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      edonkey0.length = 9727994L;
      byte[] byteArray0 = new byte[6];
      edonkey0.update(byteArray0);
      String string0 = edonkey0.getHexValue();
      assertEquals("82c1fb65386fe0a2675ebb38813227fc", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      byte[] byteArray0 = new byte[5];
      edonkey0.update(byteArray0, (int) (byte) (-120), (int) (byte) (-98));
      // Undeclared exception!
      try { 
        edonkey0.getHexValue();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      edonkey0.length = (-1L);
      edonkey0.update((byte) (-112));
      assertEquals(0L, edonkey0.getValue());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Edonkey edonkey0 = new Edonkey();
      edonkey0.reset();
      assertEquals(0L, edonkey0.getValue());
  }
}
