/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:06:26 GMT 2018
 */

package com.github.arucard21.epox.webaom;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.swing.CommandModel;
import com.github.arucard21.epox.swing.JPanelCommand;
import com.github.arucard21.epox.webaom.A;
import com.github.arucard21.epox.webaom.ChiiEmu;
import com.github.arucard21.epox.webaom.net.ACon;
import com.github.arucard21.epox.webaom.net.AConE;
import com.github.arucard21.epox.webaom.net.AConS;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ChiiEmu_ESTest extends ChiiEmu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ChiiEmu chiiEmu0 = new ChiiEmu((ACon) null);
      JPanelCommand jPanelCommand0 = new JPanelCommand(chiiEmu0, "+a5,");
      chiiEmu0.setLog(jPanelCommand0);
      chiiEmu0.println(jPanelCommand0);
      assertTrue(jPanelCommand0.getFocusTraversalKeysEnabled());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ACon aCon0 = mock(ACon.class, new ViolatedAssumptionAnswer());
      ChiiEmu chiiEmu0 = new ChiiEmu(aCon0);
      chiiEmu0.println("api.anidb.net");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = ChiiEmu.getS(3);
      assertEquals("!storage anime/aid, group/gid/all, all/upto x/x, text", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = ChiiEmu.getS(1);
      assertEquals("STATE: usage: !state <anime> <epnumber> <state>, !state <fid> <state>, !state <ed2k link> <state>, !state last <state>, epnumber may be 'all' or 'upto <epno>'. State is: unknown/hdd/cd/deleted.", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = ChiiEmu.getS(143);
      assertEquals("NOO!", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = ChiiEmu.getS(0);
      assertEquals("WATCHED: usage: !watched <anime> <epnumber>, !state <fid>, !state <ed2k link>, epnumber may be 'all', 'upto <epno>' or 'none'.", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JPanelCommand jPanelCommand0 = new JPanelCommand((CommandModel) null, "");
      AConS aConS0 = new AConS("NOO!", 0, 1005, 0, 0, 336, true);
      AConE aConE0 = new AConE(jPanelCommand0, aConS0);
      ChiiEmu chiiEmu0 = new ChiiEmu(aConE0);
      chiiEmu0.setLog(jPanelCommand0);
      chiiEmu0.println((Object) null);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JPanelCommand jPanelCommand0 = new JPanelCommand((CommandModel) null, "");
      AConS aConS0 = new AConS("NOO!", 0, 1005, 0, 0, 336, true);
      AConE aConE0 = new AConE(jPanelCommand0, aConS0);
      ChiiEmu chiiEmu0 = new ChiiEmu(aConE0);
      chiiEmu0.handleCommand("NOO!");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommandModel commandModel0 = mock(CommandModel.class, new ViolatedAssumptionAnswer());
      JPanelCommand jPanelCommand0 = new JPanelCommand(commandModel0, "@HGKa6Cy_|H6G-z}IF");
      AConS aConS0 = new AConS("", 668, 668, 668, (-362), 50, true);
      ACon aCon0 = new ACon(jPanelCommand0, aConS0);
      ChiiEmu chiiEmu0 = new ChiiEmu(aCon0);
      chiiEmu0.handleCommand("!font");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CommandModel commandModel0 = mock(CommandModel.class, new ViolatedAssumptionAnswer());
      JPanelCommand jPanelCommand0 = new JPanelCommand(commandModel0, "@HGKa6Cy_|H6G-z}IF");
      AConS aConS0 = new AConS("", 668, 668, 668, (-362), 50, true);
      ACon aCon0 = new ACon(jPanelCommand0, aConS0);
      ChiiEmu chiiEmu0 = new ChiiEmu(aCon0);
      // Undeclared exception!
      try { 
        chiiEmu0.handleCommand("!fonth ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.swing.SwingUtilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommandModel commandModel0 = mock(CommandModel.class, new ViolatedAssumptionAnswer());
      JPanelCommand jPanelCommand0 = new JPanelCommand(commandModel0, "\"D8dlsC;}H;i{;");
      AConS aConS0 = new AConS(">-**", (-726), 1, 2401, (-726), (-1282), false);
      AConE aConE0 = new AConE(jPanelCommand0, aConS0);
      ChiiEmu chiiEmu0 = new ChiiEmu(aConE0);
      A.conn = aConE0;
      chiiEmu0.handleCommand("{EN{wWR");
      chiiEmu0.handleCommand("com.github.arucard21.epox.webaom.FileHandler$FileFilter1");
  }
}
