/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:08:06 GMT 2018
 */

package com.github.arucard21.epox.webaom;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.arucard21.epox.webaom.Hyper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Hyper_ESTest extends Hyper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Hyper.dec("<a href=\"F00000\u0001006699\u0001000080\">F00000\u0001006699\u0001000080</a>");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = Hyper.color("Vj;+vV!^Q@nH", "5");
      assertEquals("<font color=#Vj;+vV!^Q@nH>5</font>", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Hyper.dec("<a href=\"F00000\u0001006699\u0001000080\">com.github.arucard21.epox.webaom.HypeQ</a>");
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Hyper.dec("F00000\u0001006699\u0001000080");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Hyper.dec((String) null);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Hyper.dec("kZ-j?[\"}|fs");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = Hyper.name((Object) "<font color=#F00000>kZ-j?[\"}|fs</font>");
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = Hyper.name((Object) null);
      assertEquals("null", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = Hyper.href("F00000\u0001006699\u0001000080", "com.github.arucard21.epox.webaom.HypeQ");
      assertEquals("<a href=\"F00000\u0001006699\u0001000080\">com.github.arucard21.epox.webaom.HypeQ</a>", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = Hyper.enc();
      assertEquals("F00000\u0001006699\u0001000080", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = Hyper.error("kZ-j?[\"}|fs");
      assertEquals("<font color=#F00000>kZ-j?[\"}|fs</font>", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = Hyper.number((-2809));
      assertEquals("<font color=#000080>-2809</font>", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = Hyper.number("F00000\u0001006699\u0001000080");
      assertEquals("<font color=#000080>F00000\u0001006699\u0001000080</font>", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String string0 = Hyper.name("F00000\u0001006699\u0001000080");
      assertEquals("<font color=#006699>F00000\u0001006699\u0001000080</font>", string0);
  }
}
