/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:05:04 GMT 2018
 */

package com.github.arucard21.epox.webaom;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.arucard21.epox.webaom.JobCnt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JobCnt_ESTest extends JobCnt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JobCnt jobCnt0 = new JobCnt();
      jobCnt0.register((-1115), (-1115), 16777217, (-1115));
      jobCnt0.register(1202, 363, (-470), (-1841));
      int int0 = jobCnt0.getProgress();
      assertEquals(333, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JobCnt jobCnt0 = new JobCnt();
      jobCnt0.register(50331649, 0, (-1099), 0);
      jobCnt0.register(50331649, 269, 3550, 1040);
      int int0 = jobCnt0.getProgress();
      assertEquals((-1000), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JobCnt jobCnt0 = new JobCnt();
      jobCnt0.reset();
      assertEquals(0, jobCnt0.getProgress());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JobCnt jobCnt0 = new JobCnt();
      jobCnt0.register(16777224, 16777224, 16777224, (-60));
      assertEquals(0, jobCnt0.getProgress());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      JobCnt jobCnt0 = new JobCnt();
      jobCnt0.register(0, (-1072), 0, 50331615);
      assertEquals(0, jobCnt0.getProgress());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JobCnt jobCnt0 = new JobCnt();
      jobCnt0.register(309, 309, 309, 50331615);
      assertEquals(0, jobCnt0.getProgress());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      JobCnt jobCnt0 = new JobCnt();
      String string0 = jobCnt0.getStatus();
      assertEquals("fin=0 dio=0 nio=0 err=0 hlt=0  tot=0", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      JobCnt jobCnt0 = new JobCnt();
      int int0 = jobCnt0.getProgress();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      JobCnt jobCnt0 = new JobCnt();
      jobCnt0.register(50331615, 309, 50331615, 131072);
      int int0 = jobCnt0.getProgress();
      assertEquals(0, int0);
  }
}
