/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Apr 13 20:03:33 GMT 2018
 */

package com.github.arucard21.epox.webaom;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class JobList_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.github.arucard21.epox.webaom.JobList"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "/home/riaas/docs/Projects_Github/webaom"); 
    java.lang.System.setProperty("user.home", "/home/riaas"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "riaas"); 
    java.lang.System.setProperty("user.timezone", "Europe/Amsterdam"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(JobList_ESTest_scaffolding.class.getClassLoader() ,
      "com.github.arucard21.epox.webaom.ui.JPanelMain$RecDir",
      "jonelo.jacksum.algorithm.AbstractChecksum",
      "com.github.arucard21.epox.webaom.ui.JPanelMain$ExImp",
      "com.github.arucard21.epox.webaom.Job",
      "com.github.arucard21.epox.util.HashContainer",
      "jonelo.jacksum.algorithm.MD",
      "com.github.arucard21.epox.webaom.Options",
      "com.github.arucard21.epox.webaom.data.AFile",
      "com.github.arucard21.epox.webaom.ui.JPanelMain$1",
      "com.github.arucard21.epox.webaom.ui.JPanelOptRls",
      "com.github.arucard21.epox.swing.JComboBoxLF$2",
      "com.github.arucard21.epox.swing.JComboBoxLF$1",
      "com.github.arucard21.epox.swing.CommandModel",
      "com.github.arucard21.epox.webaom.Cache$MyMap",
      "com.github.arucard21.epox.webaom.net.TagEx",
      "com.github.arucard21.epox.webaom.JobCnt",
      "gnu.crypto.hash.IMessageDigest",
      "com.github.arucard21.epox.webaom.data.Base",
      "com.github.arucard21.epox.webaom.data.Group",
      "com.github.arucard21.epox.webaom.ui.RowModel",
      "com.github.arucard21.epox.webaom.Cache",
      "com.github.arucard21.epox.webaom.ui.JPanelMain",
      "com.github.arucard21.epox.util.UserPass",
      "com.twmacinta.util.MD5",
      "com.github.arucard21.epox.swing.Log",
      "jonelo.jacksum.algorithm.Crc32",
      "com.github.arucard21.epox.webaom.FileHandler$FileFilter1",
      "com.github.arucard21.epox.webaom.JobList",
      "com.github.arucard21.epox.webaom.net.ACon",
      "com.github.arucard21.epox.webaom.RuleMenu",
      "com.github.arucard21.epox.webaom.ui.JEditorPaneLog$AppendFileStream",
      "com.github.arucard21.epox.swing.JPanelDebug$WinStream",
      "com.github.arucard21.epox.webaom.ui.JPopupMenuM",
      "com.github.arucard21.epox.swing.JPanelCommand",
      "com.github.arucard21.epox.webaom.DiskIO",
      "com.github.arucard21.epox.webaom.NetIO",
      "com.github.arucard21.epox.webaom.ui.JPanelJobs",
      "com.github.arucard21.epox.swing.TableSorter",
      "com.github.arucard21.epox.util.TTH",
      "com.github.arucard21.epox.swing.JScrollTable",
      "com.github.arucard21.epox.swing.JComboBoxLF",
      "com.github.arucard21.epox.webaom.net.AConEx",
      "com.github.arucard21.epox.webaom.DB",
      "com.github.arucard21.epox.webaom.data.AMap",
      "jonelo.jacksum.algorithm.Edonkey",
      "com.github.arucard21.epox.webaom.A",
      "com.github.arucard21.epox.webaom.data.AG",
      "com.github.arucard21.epox.webaom.ui.JPanelOptMyl",
      "com.github.arucard21.epox.webaom.net.AConR",
      "com.github.arucard21.epox.webaom.data.Mylist",
      "com.github.arucard21.epox.util.DSData",
      "com.github.arucard21.epox.webaom.net.AConE",
      "com.github.arucard21.epox.webaom.ui.JEditorPaneLog",
      "com.github.arucard21.epox.webaom.data.Path",
      "com.twmacinta.util.MD5State",
      "com.github.arucard21.epox.swing.UniqueStringList",
      "com.github.arucard21.epox.webaom.ui.JPanelOptCon",
      "com.github.arucard21.epox.webaom.ui.TableModelAlt",
      "com.github.arucard21.epox.util.LinkedHash$Node",
      "com.github.arucard21.epox.webaom.ui.JTableJobs",
      "com.github.arucard21.epox.swing.TableModelSortable",
      "com.github.arucard21.epox.av.FileInfo$MyHandler",
      "com.github.arucard21.epox.webaom.ui.JPanelAlt",
      "com.github.arucard21.epox.webaom.FileHandler",
      "com.github.arucard21.epox.av.FileInfo",
      "com.github.arucard21.epox.webaom.data.Anime",
      "com.github.arucard21.epox.webaom.ui.JTreeTableR",
      "com.github.arucard21.epox.webaom.data.Ep",
      "com.github.arucard21.epox.webaom.Rules",
      "com.github.arucard21.epox.swing.JPanelDebug",
      "com.github.arucard21.epox.util.U",
      "com.github.arucard21.epox.util.LinkedHash",
      "com.github.arucard21.epox.webaom.ui.TableModelJobs",
      "com.github.arucard21.epox.webaom.ui.JPanelMain$InitDB",
      "com.github.arucard21.epox.webaom.ui.TableModelDS",
      "com.github.arucard21.epox.webaom.ui.JPanelOptDiv",
      "com.github.arucard21.epox.swing.JTableSortable"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(JobList_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.github.arucard21.epox.webaom.JobList",
      "com.github.arucard21.epox.webaom.data.Base",
      "com.github.arucard21.epox.util.UserPass",
      "com.github.arucard21.epox.webaom.A",
      "com.github.arucard21.epox.util.LinkedHash",
      "com.github.arucard21.epox.util.LinkedHash$Node",
      "com.github.arucard21.epox.webaom.DB",
      "com.github.arucard21.epox.webaom.JobCnt",
      "com.github.arucard21.epox.webaom.Rules",
      "com.github.arucard21.epox.util.DSData",
      "com.github.arucard21.epox.webaom.Cache",
      "com.github.arucard21.epox.webaom.Cache$MyMap",
      "com.github.arucard21.epox.webaom.FileHandler",
      "com.github.arucard21.epox.swing.UniqueStringList",
      "com.github.arucard21.epox.webaom.FileHandler$FileFilter1",
      "com.github.arucard21.epox.webaom.Options",
      "com.github.arucard21.epox.webaom.DiskIO",
      "com.github.arucard21.epox.webaom.NetIO",
      "com.github.arucard21.epox.webaom.ui.JPanelMain",
      "com.github.arucard21.epox.webaom.ui.JPanelOptMyl",
      "com.github.arucard21.epox.webaom.ui.JPanelMain$1",
      "com.github.arucard21.epox.webaom.ui.JPanelOptDiv",
      "com.github.arucard21.epox.swing.JComboBoxLF",
      "com.github.arucard21.epox.swing.JComboBoxLF$1",
      "com.github.arucard21.epox.swing.JComboBoxLF$2",
      "com.github.arucard21.epox.webaom.Job",
      "com.github.arucard21.epox.swing.TableModelSortable",
      "com.github.arucard21.epox.webaom.ui.TableModelJobs",
      "com.github.arucard21.epox.swing.TableSorter",
      "com.github.arucard21.epox.util.U",
      "com.github.arucard21.epox.webaom.data.AFile",
      "com.github.arucard21.epox.webaom.data.AG",
      "com.github.arucard21.epox.webaom.data.Group",
      "com.github.arucard21.epox.webaom.ui.JTreeTableR",
      "com.github.arucard21.epox.av.FileInfo",
      "com.github.arucard21.epox.av.FileInfo$MyHandler",
      "com.github.arucard21.epox.webaom.data.Ep",
      "com.github.arucard21.epox.webaom.ui.JPanelAlt",
      "com.github.arucard21.epox.webaom.ui.TableModelAlt"
    );
  }
}
