/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:08:18 GMT 2018
 */

package com.github.arucard21.epox.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.util.HashContainer;
import jonelo.jacksum.algorithm.AbstractChecksum;
import jonelo.jacksum.algorithm.Crc32;
import jonelo.jacksum.algorithm.Edonkey;
import jonelo.jacksum.algorithm.MD;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HashContainer_ESTest extends HashContainer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(690);
      String string0 = hashContainer0.toString();
      Crc32 crc32_0 = new Crc32();
      byte[] byteArray0 = new byte[1];
      crc32_0.reset();
      byte byte0 = (byte)0;
      byteArray0[0] = (byte)0;
      crc32_0.reset();
      hashContainer0.toString();
      hashContainer0.add(0, "", crc32_0);
      hashContainer0.toString();
      // Undeclared exception!
      try { 
        hashContainer0.getHex(string0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(3563);
      hashContainer0.toString();
      hashContainer0.toString();
      // Undeclared exception!
      hashContainer0.toString();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int int0 = 2376;
      HashContainer hashContainer0 = new HashContainer(2376);
      hashContainer0.toString();
      hashContainer0.toString();
      hashContainer0.toString();
      // Undeclared exception!
      try { 
        hashContainer0.getHex((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(15);
      // Undeclared exception!
      try { 
        hashContainer0.finalize();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.util.HashContainer", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(0);
      byte[] byteArray0 = new byte[4];
      byteArray0[0] = (byte)0;
      byteArray0[1] = (byte)13;
      hashContainer0.toString();
      byteArray0[2] = (byte)0;
      byteArray0[3] = (byte)1;
      hashContainer0.update(byteArray0, (byte)0, 0);
      String string0 = "";
      Crc32 crc32_0 = new Crc32();
      byte[] byteArray1 = new byte[2];
      byte byte0 = (byte)0;
      byteArray1[0] = (byte)0;
      byteArray1[1] = (byte)81;
      AbstractChecksum.format(byteArray1, true);
      // Undeclared exception!
      try { 
        hashContainer0.add(0, "", crc32_0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("com.github.arucard21.epox.util.HashContainer", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(2001);
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte) (-31);
      byteArray0[1] = (byte)15;
      byteArray0[2] = (byte)0;
      // Undeclared exception!
      try { 
        hashContainer0.update(byteArray0, 1202, (byte)15);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.util.HashContainer", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = (-1);
      HashContainer hashContainer0 = null;
      try {
        hashContainer0 = new HashContainer((-1));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.util.HashContainer", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(0);
      hashContainer0.getHex("");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(0);
      hashContainer0.finalize();
      hashContainer0.getHex((String) null);
      hashContainer0.getHex((String) null);
      hashContainer0.toString();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(0);
      hashContainer0.update((byte[]) null, 1131, 0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(0);
      Crc32 crc32_0 = new Crc32();
      // Undeclared exception!
      try { 
        hashContainer0.add(0, "0123456789abcdef", crc32_0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("com.github.arucard21.epox.util.HashContainer", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(0);
      hashContainer0.toString();
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte) (-111);
      hashContainer0.update(byteArray0, (byte) (-111), (byte) (-111));
      Crc32 crc32_0 = new Crc32();
      // Undeclared exception!
      try { 
        hashContainer0.add(0, "DH[E(@\"3@nSuW", crc32_0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("com.github.arucard21.epox.util.HashContainer", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(3919);
      byte[] byteArray0 = new byte[2];
      byteArray0[0] = (byte)1;
      byteArray0[1] = (byte) (-36);
      // Undeclared exception!
      try { 
        hashContainer0.update(byteArray0, (byte) (-36), 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.util.HashContainer", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      byteArray0[0] = (byte)1;
      byteArray0[1] = (byte) (-127);
      byteArray0[2] = (byte)2;
      byteArray0[3] = (byte) (-64);
      byteArray0[4] = (byte) (-120);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(690);
      hashContainer0.toString();
      Crc32 crc32_0 = new Crc32();
      byte[] byteArray0 = new byte[1];
      crc32_0.reset();
      byte byte0 = (byte)0;
      byteArray0[0] = (byte)0;
      crc32_0.reset();
      hashContainer0.toString();
      hashContainer0.add(0, "", crc32_0);
      hashContainer0.toString();
      hashContainer0.toString();
      // Undeclared exception!
      try { 
        hashContainer0.update(byteArray0, (-4596), (-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.zip.CRC32", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(3578);
      hashContainer0.toString();
      hashContainer0.toString();
      // Undeclared exception!
      try { 
        hashContainer0.getHex("%[IBh/iql8^.):");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HashContainer hashContainer0 = new HashContainer(855);
      // Undeclared exception!
      try { 
        hashContainer0.finalize();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.util.HashContainer", e);
      }
  }
}
