/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:10:05 GMT 2018
 */

package com.github.arucard21.epox.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.arucard21.epox.util.UserPass;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UserPass_ESTest extends UserPass_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserPass userPass0 = new UserPass((String) null, (String) null, (String) null);
      String string0 = userPass0.get(false);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UserPass userPass0 = new UserPass("", "", "");
      String string0 = userPass0.get(false);
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UserPass userPass0 = new UserPass("Ag|cl4R", ":C|Lf ?OQXu`", "Ag|cl4R");
      userPass0.set("::7774R647LQ4LITNFOE2BG3RKOE");
      String string0 = userPass0.get(true);
      assertEquals("::7774R647LQ4LITNFOE2BG3RKOE", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UserPass userPass0 = new UserPass("Ag|cl4R", ":C|Lf ?OQXu`", "Ag|cl4R");
      String string0 = userPass0.get(false);
      assertNotNull(string0);
      assertEquals("Ag|cl4R", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      UserPass userPass0 = new UserPass("Ag|cl4R", ":C|Lf ?OQXu`", "Ag|cl4R");
      userPass0.set(":C|Lf ?OQXu`");
      String string0 = userPass0.get(true);
      assertEquals("::7774R647LQ4LITNFOE2BG3RKOE", string0);
  }
}
