/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:11:16 GMT 2018
 */

package com.github.arucard21.epox.webaom.ui;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.webaom.ui.HeaderListenerAlt;
import com.github.arucard21.epox.webaom.ui.JTreeTableR;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseWheelEvent;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HeaderListenerAlt_ESTest extends HeaderListenerAlt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TableColumnModel tableColumnModel0 = mock(TableColumnModel.class, new ViolatedAssumptionAnswer());
      doReturn((-1332)).when(tableColumnModel0).getColumnCount();
      JTable jTable0 = mock(JTable.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(jTable0).convertColumnIndexToModel(anyInt());
      JTableHeader jTableHeader0 = mock(JTableHeader.class, new ViolatedAssumptionAnswer());
      doReturn(1202, 0).when(jTableHeader0).columnAtPoint(any(java.awt.Point.class));
      doReturn(jTable0, (JTable) null).when(jTableHeader0).getTable();
      JTreeTableR jTreeTableR0 = mock(JTreeTableR.class, new ViolatedAssumptionAnswer());
      doReturn(tableColumnModel0).when(jTreeTableR0).getColumnModel();
      doReturn(jTableHeader0).when(jTreeTableR0).getTableHeader();
      HeaderListenerAlt headerListenerAlt0 = new HeaderListenerAlt(jTreeTableR0);
      Point point0 = mock(Point.class, new ViolatedAssumptionAnswer());
      MouseEvent mouseEvent0 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn(point0).when(mouseEvent0).getPoint();
      headerListenerAlt0.mouseClicked(mouseEvent0);
      MouseEvent mouseEvent1 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn((Point) null).when(mouseEvent1).getPoint();
      // Undeclared exception!
      try { 
        headerListenerAlt0.mouseClicked(mouseEvent1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.HeaderListenerAlt", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TableColumnModel tableColumnModel0 = mock(TableColumnModel.class, new ViolatedAssumptionAnswer());
      doReturn((-1424)).when(tableColumnModel0).getColumnCount();
      JTable jTable0 = mock(JTable.class, new ViolatedAssumptionAnswer());
      doReturn((-1424)).when(jTable0).convertColumnIndexToModel(anyInt());
      JTableHeader jTableHeader0 = mock(JTableHeader.class, new ViolatedAssumptionAnswer());
      doReturn((-1424)).when(jTableHeader0).columnAtPoint(any(java.awt.Point.class));
      doReturn(jTable0).when(jTableHeader0).getTable();
      JTreeTableR jTreeTableR0 = mock(JTreeTableR.class, new ViolatedAssumptionAnswer());
      doReturn(tableColumnModel0).when(jTreeTableR0).getColumnModel();
      doReturn(jTableHeader0).when(jTreeTableR0).getTableHeader();
      HeaderListenerAlt headerListenerAlt0 = new HeaderListenerAlt(jTreeTableR0);
      MouseEvent mouseEvent0 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      MouseEvent mouseEvent1 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn((-1424)).when(mouseEvent1).getButton();
      headerListenerAlt0.mouseReleased(mouseEvent1);
      MouseEvent mouseEvent2 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      headerListenerAlt0.mouseMoved(mouseEvent2);
      headerListenerAlt0.mouseDragged(mouseEvent0);
      MouseEvent mouseEvent3 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      headerListenerAlt0.mouseEntered(mouseEvent3);
      MouseEvent mouseEvent4 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn(9990).when(mouseEvent4).getButton();
      headerListenerAlt0.mousePressed(mouseEvent4);
      Point point0 = mock(Point.class, new ViolatedAssumptionAnswer());
      MouseEvent mouseEvent5 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn(point0).when(mouseEvent5).getPoint();
      headerListenerAlt0.mouseClicked(mouseEvent5);
      // Undeclared exception!
      try { 
        headerListenerAlt0.mouseClicked((MouseEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.HeaderListenerAlt", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TableColumn tableColumn0 = mock(TableColumn.class, new ViolatedAssumptionAnswer());
      TableColumnModel tableColumnModel0 = mock(TableColumnModel.class, new ViolatedAssumptionAnswer());
      doReturn(tableColumn0).when(tableColumnModel0).getColumn(anyInt());
      doReturn(2097152, 0).when(tableColumnModel0).getColumnCount();
      JTableHeader jTableHeader0 = mock(JTableHeader.class, new ViolatedAssumptionAnswer());
      JTreeTableR jTreeTableR0 = mock(JTreeTableR.class, new ViolatedAssumptionAnswer());
      doReturn(tableColumnModel0).when(jTreeTableR0).getColumnModel();
      doReturn((JTableHeader) null).when(jTreeTableR0).getTableHeader();
      HeaderListenerAlt headerListenerAlt0 = null;
      try {
        headerListenerAlt0 = new HeaderListenerAlt(jTreeTableR0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.HeaderListenerAlt", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TableColumnModel tableColumnModel0 = mock(TableColumnModel.class, new ViolatedAssumptionAnswer());
      doReturn((-1424)).when(tableColumnModel0).getColumnCount();
      JTable jTable0 = mock(JTable.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(jTable0).convertColumnIndexToModel(anyInt());
      JTableHeader jTableHeader0 = mock(JTableHeader.class, new ViolatedAssumptionAnswer());
      doReturn(706).when(jTableHeader0).columnAtPoint(any(java.awt.Point.class));
      doReturn(jTable0).when(jTableHeader0).getTable();
      JTreeTableR jTreeTableR0 = mock(JTreeTableR.class, new ViolatedAssumptionAnswer());
      doReturn(tableColumnModel0).when(jTreeTableR0).getColumnModel();
      doReturn(jTableHeader0).when(jTreeTableR0).getTableHeader();
      HeaderListenerAlt headerListenerAlt0 = new HeaderListenerAlt(jTreeTableR0);
      assertNotNull(headerListenerAlt0);
      
      MouseEvent mouseEvent0 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      MouseEvent mouseEvent1 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn((-110)).when(mouseEvent1).getButton();
      headerListenerAlt0.mouseReleased(mouseEvent1);
      MouseEvent mouseEvent2 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      headerListenerAlt0.mouseMoved(mouseEvent2);
      headerListenerAlt0.mouseDragged(mouseEvent0);
      MouseEvent mouseEvent3 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      headerListenerAlt0.mouseEntered(mouseEvent3);
      MouseEvent mouseEvent4 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn((-1424)).when(mouseEvent4).getButton();
      headerListenerAlt0.mousePressed(mouseEvent4);
      Point point0 = mock(Point.class, new ViolatedAssumptionAnswer());
      MouseEvent mouseEvent5 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn(point0).when(mouseEvent5).getPoint();
      headerListenerAlt0.mouseClicked(mouseEvent5);
      // Undeclared exception!
      try { 
        headerListenerAlt0.mouseClicked((MouseEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.HeaderListenerAlt", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TableColumnModel tableColumnModel0 = mock(TableColumnModel.class, new ViolatedAssumptionAnswer());
      doReturn((-1424)).when(tableColumnModel0).getColumnCount();
      JTableHeader jTableHeader0 = mock(JTableHeader.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(jTableHeader0).columnAtPoint(any(java.awt.Point.class));
      doReturn((JTable) null).when(jTableHeader0).getTable();
      JTreeTableR jTreeTableR0 = mock(JTreeTableR.class, new ViolatedAssumptionAnswer());
      doReturn(tableColumnModel0).when(jTreeTableR0).getColumnModel();
      doReturn(jTableHeader0).when(jTreeTableR0).getTableHeader();
      HeaderListenerAlt headerListenerAlt0 = new HeaderListenerAlt(jTreeTableR0);
      assertNotNull(headerListenerAlt0);
      
      MouseEvent mouseEvent0 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      MouseEvent mouseEvent1 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(mouseEvent1).getButton();
      headerListenerAlt0.mouseReleased(mouseEvent1);
      MouseEvent mouseEvent2 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      headerListenerAlt0.mouseMoved(mouseEvent2);
      headerListenerAlt0.mouseDragged(mouseEvent0);
      MouseEvent mouseEvent3 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      headerListenerAlt0.mouseEntered(mouseEvent3);
      MouseEvent mouseEvent4 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(mouseEvent4).getButton();
      headerListenerAlt0.mousePressed(mouseEvent4);
      MouseEvent mouseEvent5 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn((Point) null).when(mouseEvent5).getPoint();
      // Undeclared exception!
      try { 
        headerListenerAlt0.mouseClicked(mouseEvent5);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.HeaderListenerAlt", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TableColumnModel tableColumnModel0 = mock(TableColumnModel.class, new ViolatedAssumptionAnswer());
      doReturn((TableColumn) null).when(tableColumnModel0).getColumn(anyInt());
      doReturn(791).when(tableColumnModel0).getColumnCount();
      JTableHeader jTableHeader0 = mock(JTableHeader.class, new ViolatedAssumptionAnswer());
      JTreeTableR jTreeTableR0 = mock(JTreeTableR.class, new ViolatedAssumptionAnswer());
      doReturn(tableColumnModel0).when(jTreeTableR0).getColumnModel();
      HeaderListenerAlt headerListenerAlt0 = null;
      try {
        headerListenerAlt0 = new HeaderListenerAlt(jTreeTableR0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.HeaderListenerAlt", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TableColumnModel tableColumnModel0 = mock(TableColumnModel.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(tableColumnModel0).getColumnCount();
      JTreeTableR jTreeTableR0 = mock(JTreeTableR.class, new ViolatedAssumptionAnswer());
      doReturn(tableColumnModel0).when(jTreeTableR0).getColumnModel();
      doReturn((JTableHeader) null).when(jTreeTableR0).getTableHeader();
      HeaderListenerAlt headerListenerAlt0 = null;
      try {
        headerListenerAlt0 = new HeaderListenerAlt(jTreeTableR0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.HeaderListenerAlt", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      JTreeTableR jTreeTableR0 = mock(JTreeTableR.class, new ViolatedAssumptionAnswer());
      doReturn((TableColumnModel) null).when(jTreeTableR0).getColumnModel();
      HeaderListenerAlt headerListenerAlt0 = null;
      try {
        headerListenerAlt0 = new HeaderListenerAlt(jTreeTableR0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.HeaderListenerAlt", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      TableColumn tableColumn0 = mock(TableColumn.class, new ViolatedAssumptionAnswer());
      TableColumn tableColumn1 = mock(TableColumn.class, new ViolatedAssumptionAnswer());
      TableColumnModel tableColumnModel0 = mock(TableColumnModel.class, new ViolatedAssumptionAnswer());
      doReturn(tableColumn0).when(tableColumnModel0).getColumn(anyInt());
      doReturn(2097152, 0).when(tableColumnModel0).getColumnCount();
      JTable jTable0 = mock(JTable.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(jTable0).convertColumnIndexToModel(anyInt());
      JTable jTable1 = mock(JTable.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(jTable1).convertColumnIndexToModel(anyInt());
      JTable jTable2 = mock(JTable.class, new ViolatedAssumptionAnswer());
      JTableHeader jTableHeader0 = mock(JTableHeader.class, new ViolatedAssumptionAnswer());
      doReturn(1246, 2097152).when(jTableHeader0).columnAtPoint(any(java.awt.Point.class));
      doReturn(jTable0, jTable1).when(jTableHeader0).getTable();
      JTreeTableR jTreeTableR0 = mock(JTreeTableR.class, new ViolatedAssumptionAnswer());
      doReturn(tableColumnModel0).when(jTreeTableR0).getColumnModel();
      doReturn(jTableHeader0).when(jTreeTableR0).getTableHeader();
      HeaderListenerAlt headerListenerAlt0 = new HeaderListenerAlt(jTreeTableR0);
      Point point0 = mock(Point.class, new ViolatedAssumptionAnswer());
      MouseEvent mouseEvent0 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn(point0).when(mouseEvent0).getPoint();
      headerListenerAlt0.mouseClicked(mouseEvent0);
      Point point1 = mock(Point.class, new ViolatedAssumptionAnswer());
      MouseEvent mouseEvent1 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn(point1).when(mouseEvent1).getPoint();
      headerListenerAlt0.mouseClicked(mouseEvent1);
      MouseEvent mouseEvent2 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn((-1917)).when(mouseEvent2).getButton();
      headerListenerAlt0.mouseReleased(mouseEvent2);
      MouseEvent mouseEvent3 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      headerListenerAlt0.mouseMoved(mouseEvent3);
      MouseEvent mouseEvent4 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      headerListenerAlt0.mouseEntered(mouseEvent4);
  }
}
