/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 20:09:26 GMT 2018
 */

package com.github.arucard21.epox.webaom.ui;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.webaom.JobList;
import com.github.arucard21.epox.webaom.ui.MouseAdapterJob;
import com.github.arucard21.epox.webaom.ui.TableModelJobs;
import java.awt.event.MouseEvent;
import javax.swing.JTable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MouseAdapterJob_ESTest extends MouseAdapterJob_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JTable jTable0 = new JTable();
      JobList jobList0 = mock(JobList.class, new ViolatedAssumptionAnswer());
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      JobList jobList1 = mock(JobList.class, new ViolatedAssumptionAnswer());
      MouseAdapterJob mouseAdapterJob0 = new MouseAdapterJob(jTable0, tableModelJobs0, jobList1);
      // Undeclared exception!
      try { 
        mouseAdapterJob0.mouseClicked((MouseEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.MouseAdapterJob", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JTable jTable0 = new JTable();
      JobList jobList0 = mock(JobList.class, new ViolatedAssumptionAnswer());
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      JobList jobList1 = mock(JobList.class, new ViolatedAssumptionAnswer());
      MouseAdapterJob mouseAdapterJob0 = new MouseAdapterJob(jTable0, tableModelJobs0, jobList1);
      MouseEvent mouseEvent0 = mock(MouseEvent.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(mouseEvent0).getClickCount();
      mouseAdapterJob0.mouseClicked(mouseEvent0);
  }
}
