/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 13 19:58:35 GMT 2018
 */

package com.github.arucard21.epox.webaom.ui;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.arucard21.epox.webaom.JobList;
import com.github.arucard21.epox.webaom.ui.TableModelJobs;
import javax.swing.JTable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableModelJobs_ESTest extends TableModelJobs_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      tableModelJobs0.getColumnClass(11);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      tableModelJobs0.getRowCount();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TableModelJobs tableModelJobs0 = new TableModelJobs((JobList) null);
      tableModelJobs0.getColumnName(0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      tableModelJobs0.getColumnIndex("grn");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TableModelJobs tableModelJobs0 = new TableModelJobs((JobList) null);
      tableModelJobs0.getColumnCount();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TableModelJobs tableModelJobs0 = new TableModelJobs((JobList) null);
      // Undeclared exception!
      try { 
        tableModelJobs0.getRowCount();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TableModelJobs tableModelJobs0 = new TableModelJobs((JobList) null);
      // Undeclared exception!
      try { 
        tableModelJobs0.getJobs(1331);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      // Undeclared exception!
      try { 
        tableModelJobs0.getColumnName(94);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 94
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        TableModelJobs.formatTable((JTable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JobList jobList0 = new JobList();
      Object[][] objectArray0 = new Object[6][9];
      Object[] objectArray1 = new Object[8];
      objectArray1[0] = (Object) jobList0;
      objectArray1[1] = (Object) jobList0;
      objectArray1[2] = (Object) jobList0;
      objectArray1[3] = (Object) jobList0;
      objectArray1[4] = (Object) jobList0;
      objectArray1[5] = (Object) jobList0;
      objectArray1[6] = (Object) jobList0;
      objectArray1[7] = objectArray1[5];
      JTable jTable0 = new JTable(objectArray0, objectArray1);
      // Undeclared exception!
      try { 
        TableModelJobs.formatTable(jTable0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 8 >= 8
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      // Undeclared exception!
      try { 
        jobList0.jlm.convertRows((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      jobList0.jlm.getValueAt(2110, (-1));
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      jobList0.jlm.reset();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      int[] intArray0 = new int[3];
      jobList0.jlm.convertRows(intArray0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      JTable jTable0 = new JTable(jobList0.jlm);
      TableModelJobs.formatTable(jTable0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      jobList0.jlm.getColumnIndex("#");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      jobList0.jlm.getColumnIndex("_i>*H]xIUMz]K 0Flw:");
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      // Undeclared exception!
      try { 
        jobList0.jlm.getValueAt(15, 21);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      // Undeclared exception!
      try { 
        tableModelJobs0.getValueAt(2, 14);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      // Undeclared exception!
      try { 
        tableModelJobs0.getValueAt(2, 13);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      // Undeclared exception!
      try { 
        jobList0.jlm.getValueAt(22, 10);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      // Undeclared exception!
      try { 
        tableModelJobs0.getValueAt((-1), 9);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      // Undeclared exception!
      try { 
        jobList0.jlm.getValueAt(3673, 7);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      // Undeclared exception!
      try { 
        tableModelJobs0.getValueAt((-79), 6);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      // Undeclared exception!
      try { 
        tableModelJobs0.getValueAt(2, 5);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      // Undeclared exception!
      try { 
        jobList0.jlm.getValueAt(2, 4);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      // Undeclared exception!
      try { 
        tableModelJobs0.getValueAt(2, 3);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      // Undeclared exception!
      try { 
        tableModelJobs0.getValueAt(2, 2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      // Undeclared exception!
      try { 
        tableModelJobs0.getValueAt(132, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      tableModelJobs0.getValueAt(2, 0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      // Undeclared exception!
      try { 
        jobList0.jlm.getValueAt((-1), 12);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      // Undeclared exception!
      try { 
        tableModelJobs0.getValueAt(4346, 11);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      jobList0.jlm.getColumnClass(34);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      jobList0.jlm.getColumnClass(7);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      tableModelJobs0.convertRow(2162708);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      jobList0.jlm.getJobs(29);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      tableModelJobs0.isCellEditable(2, (-388));
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs(jobList0);
      jobList0.jlm = tableModelJobs0;
      jobList0.jlm.updateRow(24);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      JobList jobList0 = new JobList();
      TableModelJobs tableModelJobs0 = new TableModelJobs((JobList) null);
      jobList0.jlm = tableModelJobs0;
      JTable jTable0 = new JTable(jobList0.jlm);
      // Undeclared exception!
      try { 
        tableModelJobs0.insertJob(1735328473);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.github.arucard21.epox.webaom.ui.TableModelJobs", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      TableModelJobs tableModelJobs0 = new TableModelJobs((JobList) null);
      tableModelJobs0.insertJob(1735328473);
      assertEquals(15, TableModelJobs.AROM);
  }
}
